import Header from '@/components/layout/header'
import TransitionPage from '@/components/transition-page'
import SmoothScrolling from '@/lib/SmoothScrolling'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className + ''}>
        <Header />
        <SmoothScrolling>
          <TransitionPage>{children}</TransitionPage>
        </SmoothScrolling>
        {/* <AnimationCursor /> */}
      </body>
    </html>
  )
}
